typeset -F SECONDS=0
export START_TIME=$SECONDS

source ~/.dotfiles/zsh/core.zsh
source $DOTF/zsh/aliases.zsh
source $DOTF/zsh/completion.zsh
source $DOTF/zsh/prompt.zsh

duration=$((($SECONDS - $START_TIME) * 1000))
echo "\033[1;30m($(printf '%.2f' $duration)ms)\033[0m"
