typeset -F SECONDS=0
export START_TIME=$SECONDS

export DOTF=~/.dotfiles

source $DOTF/zsh/core.zsh
source $DOTF/zsh/settings.zsh
source $DOTF/zsh/aliases.zsh
source $DOTF/zsh/completion.zsh
source $DOTF/zsh/prompt.zsh
source $DOTF/zsh/history.zsh

duration=$((($SECONDS - $START_TIME) * 1000))
echo "\033[1;30m($(printf '%.2f' $duration)ms)\033[0m"

PATH="$PATH:$DOTF/in_path"

NPM_PACKAGES="${HOME}/.npm-packages"
PATH="$NPM_PACKAGES/bin:$PATH"
PATH="$PATH:`yarn global bin`"

# Unset manpath so we can inherit from /etc/manpath via the `manpath` command
unset MANPATH # delete if you already modified MANPATH elsewhere in your config
export MANPATH="$NPM_PACKAGES/share/man:$(manpath)"

export NVM_DIR="${HOME}/.nvm"
. "/usr/local/opt/nvm/nvm.sh"

export PATH="/usr/local/sbin:$PATH"

# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /Users/idanwe/.nvm/versions/node/v8.5.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /Users/idanwe/.nvm/versions/node/v8.5.0/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /Users/idanwe/.nvm/versions/node/v8.5.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /Users/idanwe/.nvm/versions/node/v8.5.0/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh
